services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-server
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
