services:
  agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    restart: always
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9001
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - ${DOCKER_VOLUMES:-/var/lib/docker/volumes}:/var/lib/docker/volumes
    ports:
      - "9001:9001"
    networks:
      - portainer_agent_network

networks:
  portainer_agent_network:
    driver: bridge
